debug step find requirements.txt (3)

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -41,6 +41,13 @@ jobs:
           with:
             python-version: "3.10"
 
+        - name: list files for debugging
+          run: |
+            pwd 
+            ls -la
+            ls -la requirements.txt || echo "requirements.txt not found in current directory"
+
+
         - name: Install dependencies
           run: | 
             pip install -r requirements.txt
